"""Generate LaTeX tables from paper/data/*.csv files.

Usage:
    uv run python paper/build_tables.py

Reads CSVs from paper/data/ and writes .tex files to paper/tables/.
"""

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"
TABLES = ROOT / "tables"


def fmt(val: str, decimals: int = 3, bold: bool = False) -> str:
    """Format a numeric string for LaTeX."""
    if not val or val == "---":
        return "---"
    f = float(val)
    if f > 100:  # e.g. budget_utilization > 1 means full-corpus
        s = f"{f:.1f}"
    elif f >= 1.0 - 1e-9:  # 1.000
        s = f"{f:.3f}"
    else:
        s = f".{f:.{decimals}f}"[2:]  # strip leading "0", show ".XXX"
    if bold:
        return rf"\textbf{{{s}}}"
    return s


def find_best(rows: list[dict], col: str, exclude: set[str] | None = None,
              higher_is_better: bool = True) -> int:
    """Return index of best non-diagnostic row for a column."""
    best_idx = -1
    best_val = float("-inf") if higher_is_better else float("inf")
    for i, r in enumerate(rows):
        if exclude and r.get("selector", r.get("edge_scorer", "")) in exclude:
            continue
        v = r.get(col, "")
        if not v:
            continue
        fv = float(v)
        if (higher_is_better and fv > best_val) or (not higher_is_better and fv < best_val):
            best_val = fv
            best_idx = i
    return best_idx


def build_table3():
    """Table 3: 2Wiki calibration baseline ordering."""
    csv_path = DATA / "table3-2wiki-baseline.csv"
    with open(csv_path) as f:
        rows = list(csv.DictReader(f))

    # Find best non-diagnostic selector for each metric
    diagnostics = {"Oracle", "Full Corpus"}
    best_f1 = find_best(rows, "support_f1", diagnostics)
    best_p = find_best(rows, "support_precision", diagnostics)
    best_r = find_best(rows, "support_recall", diagnostics)

    # Count how many rows have data for each column (for note about missing data)
    has_all_data = all(r["support_precision"] for r in rows if r["selector"] not in diagnostics)

    lines = [
        r"% Auto-generated by paper/build_tables.py from paper/data/table3-2wiki-baseline.csv",
        r"% Source runs: 2wiki-baseline-retest-s100-v1 (88 cases), 2wiki-single-path-edge-ablation-s100-v1 (100 cases)",
        r"",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{%",
        r"  2WikiMultihopQA calibration summary (dev set, token budget = 256).",
        r"  \textsc{Single-Path Walk} uses the \texttt{st\_future\_heavy} scorer profile with lookahead 2.",
        r"  All selectors use sentence-transformer seeds (\texttt{multi-qa-MiniLM-L6-cos-v1})",
        r"  and \texttt{budget\_fill\_relative\_drop}.%",
        r"}",
        r"\label{tab:2wiki-calibration}",
        r"\smallskip",
        r"\begin{tabular}{@{}l c c c c@{}}",
        r"\toprule",
        r"\textbf{Selector} & \textbf{Supp.\ F1} & \textbf{Precision} & \textbf{Recall} & \textbf{Budget Util.} \\",
        r"\midrule",
    ]

    for i, r in enumerate(rows):
        name = r["selector"]
        is_diag = name in diagnostics

        # Format values, bold if best among non-diagnostics
        f1 = fmt(r["support_f1"], bold=(i == best_f1))
        p = fmt(r["support_precision"], bold=(i == best_p)) if r["support_precision"] else "---"
        rec = fmt(r["support_recall"], bold=(i == best_r)) if r["support_recall"] else "---"
        util = fmt(r["budget_utilization"]) if r["budget_utilization"] else "---"

        # LaTeX-escape selector name
        tex_name = rf"\textsc{{{name.split(' (')[0]}}}"
        suffix = ""
        if "(" in name:
            suffix = " (" + name.split("(", 1)[1]

        line = f"{tex_name}{suffix} & {f1} & {p} & {rec} & {util} \\\\"

        # Add midrules around diagnostic rows
        if i == 0:  # Oracle
            lines.append(line)
            lines.append(r"\midrule")
        elif name == "Full Corpus":
            lines.append(r"\midrule")
            lines.append(line)
        else:
            lines.append(line)

    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ])

    out_path = TABLES / "2wiki-baseline.tex"
    out_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {out_path}")


def build_table6():
    """Table 6: Edge-scorer ablation."""
    csv_path = DATA / "table6-edge-scorer-ablation.csv"
    with open(csv_path) as f:
        rows = list(csv.DictReader(f))

    best_f1 = find_best(rows, "support_f1")
    best_r = find_best(rows, "support_recall")
    best_p = find_best(rows, "support_precision")

    lines = [
        r"% Auto-generated by paper/build_tables.py from paper/data/table6-edge-scorer-ablation.csv",
        r"% Source: runs/2wiki-single-path-edge-ablation-s100-v1 (100 cases)",
        r"",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Edge-scorer ablation on 2WikiMultihopQA (100 cases, token budget = 128, single-path walk).",
        r"All variants share a top-1 sentence-transformer seed, 2-hop budget,",
        r"and \texttt{budget\_fill\_relative\_drop}.",
        r"LA = lookahead depth.}",
        r"\label{tab:edge-scorer-ablation}",
        r"\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{@{}llccccc@{}}",
        r"\toprule",
        r"\textbf{Edge Scorer} & \textbf{Profile} & \textbf{LA}",
        r"  & \textbf{Sup.~F\textsubscript{1}} & \textbf{Recall} & \textbf{Prec.} \\",
        r"\midrule",
    ]

    for i, r in enumerate(rows):
        scorer = r["edge_scorer"]
        profile = r["profile"]
        la = r["lookahead"]
        f1 = fmt(r["support_f1"], bold=(i == best_f1))
        rec = fmt(r["support_recall"], bold=(i == best_r))
        p = fmt(r["support_precision"], bold=(i == best_p))

        profile_tex = f"\\texttt{{{profile.replace('_', '\\_')}}}" if profile != "---" else "---"
        lines.append(f"{scorer:14s} & {profile_tex} & {la} & {f1} & {rec} & {p} \\\\")

    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ])

    out_path = TABLES / "edge-scorer-ablation.tex"
    out_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    TABLES.mkdir(parents=True, exist_ok=True)
    print("Building Table 3...")
    build_table3()
    print()
    print("Building Table 6...")
    build_table6()
